-- Find the number of customers in each RFM segment

SELECT
    Customer_Segment,
    COUNT(*) AS Customer_Count
FROM Customer_RFM_Final
GROUP BY Customer_Segment
ORDER BY Customer_Count DESC;
---Insight:The largest segment is Lost Customers (912), followed closely by Most Loyal Customers (905) and Loyal Customers (892).



-- Find total revenue and average customer revenue for each RFM segment

SELECT
    Customer_Segment,
    COUNT(*) AS Customer_Count,
    SUM(Monetary) AS Total_Revenue,
    AVG(Monetary) AS Average_Revenue_Per_Customer
FROM Customer_RFM_Final
GROUP BY Customer_Segment
ORDER BY Total_Revenue DESC;
--Insight:Most Loyal Customers generate the highest total revenue at approximately €5.66 million


-- Compare average customer revenue across RFM segments

SELECT
    Customer_Segment,
    AVG(Monetary) AS Average_Revenue_Per_Customer
FROM Customer_RFM_Final
GROUP BY Customer_Segment
ORDER BY Average_Revenue_Per_Customer DESC;
--Insight:Most Loyal Customers generate the highest average revenue per customer (€6,256).

-- Find the top 10 customers by total monetary value

SELECT TOP 10
    CustomerID,
    Monetary,
    Frequency,
    Recency,
    Customer_Segment
FROM Customer_RFM_Final
ORDER BY Monetary DESC;
--Insight:Customer 14646 is the highest-value customer, generating €280,206



-- Find the top 10 customers by number of orders

SELECT TOP 10
    CustomerID,
    Frequency,
    Monetary,
    Recency,
    Customer_Segment
FROM Customer_RFM_Final
ORDER BY Frequency DESC;
--Insight:Customer 12748 has the highest purchase frequency, with 209 orders

-- Calculate revenue generated by At Risk customers

SELECT
    SUM(Monetary) AS At_Risk_Revenue,
    COUNT(*) AS At_Risk_Customers
FROM Customer_RFM_Final
WHERE Customer_Segment = 'At Risk';
--Insight:At-Risk customers (418) generate approximately €732,823 in revenue, making them an important retention opportunity.

-- Calculate each customer segment's contribution to total revenue

SELECT
    Customer_Segment,
    SUM(Monetary) AS Segment_Revenue,
    ROUND(
        SUM(Monetary) * 100.0 / (SELECT SUM(Monetary) FROM Customer_RFM_Final),
        2
    ) AS Revenue_Percentage
FROM Customer_RFM_Final
GROUP BY Customer_Segment
ORDER BY Revenue_Percentage DESC;
--Insight:Most Loyal Customers contribute the largest share of revenue at 63.71%.

-- Calculate the number and percentage of inactive or at-risk customers

SELECT
    COUNT(*) AS At_Risk_Or_Lost_Customers,
    ROUND(
        COUNT(*) * 100.0 / (SELECT COUNT(*) FROM Customer_RFM_Final),
        2
    ) AS Customer_Percentage
FROM Customer_RFM_Final
WHERE Customer_Segment IN ('At Risk', 'Lost Customers');
--Insight:1,330 customers (30.66%) are either At Risk or Lost, indicating a significant customer-retention challenge.

-- Find the top 10 countries by total revenue

SELECT TOP 10
    Country,
    SUM(Revenue) AS Total_Revenue,
    COUNT(DISTINCT CustomerID) AS Customer_Count
FROM OnlineRetail
GROUP BY Country
ORDER BY Total_Revenue DESC;
--Insight:The United Kingdom is the dominant market, generating approximately €7.29 million in revenue.

-- Find the top 10 products by total revenue

SELECT TOP 10
    StockCode,
    Description,
    SUM(Revenue) AS Total_Revenue,
    SUM(Quantity) AS Total_Quantity
FROM OnlineRetail
GROUP BY StockCode, Description
ORDER BY Total_Revenue DESC;
--Insight:PAPER CRAFT, LITTLE BIRDIE is the highest-revenue product, generating approximately €168,470.

-- Find monthly revenue to identify the highest-performing months

SELECT
    YEAR(InvoiceDate) AS Sales_Year,
    MONTH(InvoiceDate) AS Sales_Month,
    SUM(Revenue) AS Total_Revenue
FROM OnlineRetail
GROUP BY
    YEAR(InvoiceDate),
    MONTH(InvoiceDate)
ORDER BY Total_Revenue DESC;
--Insight:November 2011 was the highest-revenue month, generating approximately €1.16 million

-- Compare average purchase frequency across RFM segments

SELECT
    Customer_Segment,
    AVG(Frequency) AS Average_Frequency,
    COUNT(*) AS Customer_Count
FROM Customer_RFM_Final
GROUP BY Customer_Segment
ORDER BY Average_Frequency DESC;
--Insight:Most Loyal Customers have the highest average purchase frequency at 11 orders per customer.

-- Compare average days since last purchase across RFM segments

SELECT
    Customer_Segment,
    AVG(Recency) AS Average_Recency,
    COUNT(*) AS Customer_Count
FROM Customer_RFM_Final
GROUP BY Customer_Segment
ORDER BY Average_Recency ASC;
--Insight:Most Loyal Customers have the lowest average recency at 12 days, while Lost Customers average 
--228 days since their last purchase.